# Generated by Django 6.1.1 on 2026-10-02 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_post_counted_views_post_created_date_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
